export const examples = [
  ":ExF Álgebra Lineal",
  ":ExF Métodos Numéricos (todos)",
  "RESERVADO",
  ":Calculo de una Variable - Khouri De Arciniegas, Cordelia",
  ":MANTENIMIENTO AUDIOVISUAL TI 2024-I  --  Anthony Davila",
  ":REUNIÓN TI",
  ":Simulacro de Admisión - Edgard Portocarrero",
  ":CAMBIO DE EQUIPOS ACCESS POINTS - Cristhian Blasido",
  ":Mantenimiento TI",
  ":Examen Final - Cálculo de una variable",
  ":CIUR 2024 - Matteo Stiglich",
  "BI0018-Ingeniería de Tejidos - Sec.1 - TEO - Grupo 1 - Docente\tKaren Gonzales",
  "IN0081-Modelado y Simulación de Procesos de Negocio - Sec.1 - TEO - Grupo 1 - Docente\tCintya  Garcia",
  "CC1101-Cálculo de una variable - Sec.1 - TEO - Grupo 1.06 -  ",
  "ME1011-Introducción a la Ingeniería Mecánica - Sec.1 - TEO - Grupo 1 - Docente\tOmar Bejarano",
  "CC2101-Ecuaciones Diferenciales - Sec.1 - TEO - Grupo 1.01 - Docente\tJulio Barraza",
  "GI2101-Empresa y Consumidor - Sec.1 - TEO - Grupo 1.01 - Docente\tCarlos Guevara",
  "GI2101-Empresa y Consumidor - Sec.1 - TEO - Grupo 1.02 - Docente\tCarlos Guevara",
  "GI3101-Finanzas Empresariales - Sec.1 - TEO - Grupo 1.05 - Docente\tMiguel Angel Velasquez",
  "CC1121-Introducción a la Mecánica - Sec.1 - TEO - Grupo 1.02 - Docente\tOscar Castillo",
  "IN3006-Gestión de la Calidad - Sec.1 - TEO - Grupo 1 - Docente\tAlejandro Gallegos",
  "CC1101-Cálculo de una variable - Sec.2 - TEO - Grupo 2.06 -  ",
  "CC1101-Cálculo de una variable - Sec.2 - TEO - Grupo 2.01 -  ",
  "CC1141-Química General - Sec.2 - TEO - Grupo 2.02 -  ",
  "CC1141-Química General - Sec.3 - TEO - Grupo 3.04 -  ",
  "CC1141-Química General - Sec.3 - TEO - Grupo 3.05 -  ",
  "CC1141-Química General - Sec.3 - TEO - Grupo 3.02 -  ",
  "CC1104-Cálculo Vectorial - Sec.3 - TEO - Grupo 3.02 - Docente\tMaximo Obregon",
  "HH3101-Arte y Tecnología - Sec.3 - TEO - Grupo 3 - Docente\tDiana Castillo",
  "CC1101-Cálculo de una variable - Sec.4 - TEO - Grupo 4.01 -  ",
  "CC1101-Cálculo de una variable - Sec.4 - TEO - Grupo 4.02 -  ",
  "CC1105-Estadística y Probabilidades I - Sec.12 - TEO - Grupo 12 - Docente\tJose Renom",
  "PI3103-Proyectos Interdisciplinarios 3 - Sec.17 - TEO - Grupo 17 - Docente\tJulian Valencia",
  "AM0015-Desarrollo sustentable - Sec.1 - LAB - Grupo 1.01 - Docente\tJose Manuel Cerdan",
  "AD1001-Introducción a los Negocios Digitales - Sec.1 - LAB - Grupo 1.01 - Docente\tJulian Valencia",
  "HH1102-Laboratorio de Comunicación 2 - Sec.1 - LAB - Grupo 1.01 - Docente\tAgustín Panizo",
  "AM2003-Geología - Sec.2 - LAB - Grupo 2.01 - Docente\tEdmundo Vereau",
  ":Mantenimiento SSGG - Victor Enciso",
  ":Counter Docentes",
  ":INTEGRA UTEC - Carla Chavez",
  "GH0014-Culturas de Gobernanza y Distribución de Poder - Sec.1 - TEO - Grupo 1 - Docente\tJuan Sanchez",
  "GH0015-Imagen y Marca Personal - Sec.1 - TEO - Grupo 1 - Docente\tJimena Muñoz",
  "GH0023-Business Communication - Sec.1 - TEO - Grupo 1 - Docente\tKenny Neira",
  "GH0025-English for STEAM - Sec.1 - TEO - Grupo 1 - Docente\tClaudia Teresa Cabezas",
  "HH1101-Laboratorio de Comunicación 1 - Sec.1 - TEO - Grupo 1 - Docente\tJavier Pizarro",
  "AD1101-Tendencias en tecnología - Sec.1 - TEO - Grupo 1.01 - Docente\tRafael Hospina",
  "HH1102-Laboratorio de Comunicación 2 - Sec.1 - TEO - Grupo 1 - Docente\tAgustín Panizo",
  "CC2101-Ecuaciones Diferenciales - Sec.1 - TEO - Grupo 1.02 - Docente\tOrlando Alfredo Galarza",
  "CC1143-Ciencia de los Materiales - Sec.1 - TEO - Grupo 1.07 - Docente\tLoreleyn Flor Flores",
  "CC1143-Ciencia de los Materiales - Sec.1 - TEO - Grupo 1 - Docente\tLoreleyn Flor Flores",
  "IN3004-Salud y Seguridad Ocupacional - Sec.1 - TEO - Grupo 1 - Docente\tUrsula Angelica Velazco",
  "AD8007-Agile Project Management - Sec.1 - TEO - Grupo 1 - Docente\tCecilia Del Carmen Talaviña",
  "CC1122-Fundamentos de Electricidad y Magnetismo - Sec.2 - TEO - Grupo 2.04 - Docente\tAlexander Peña",
  "EL2013-Circuitos Digitales - Sec.2 - TEO - Grupo 2 - Docente\tRuth Canahuire",
  "CS2013-Programación III - Sec.3 - TEO - Grupo 3 - Docente\tRubén Rivas",
  "CS3051-Arquitectura de Computadoras - Sec.3 - TEO - Grupo 3 - Docente\tMaria Elisia Armas",
  "HH2101-Perú: Temas de la sociedad contemporánea - Sec.5 - TEO - Grupo 5 - Docente\tCayetana Adrianzen",
  "PI3103-Proyectos Interdisciplinarios 3 - Sec.22 - TEO - Grupo 22 - Docente\tMartha Patricia Quispe",
  "GH0014-Culturas de Gobernanza y Distribución de Poder - Sec.1 - LAB - Grupo 1.01 - Docente\tJuan Sanchez",
  "GH0015-Imagen y Marca Personal - Sec.1 - LAB - Grupo 1.01 - Docente\tJimena Muñoz",
  "IN0077-Gestión de Compras y Mercados Electrónicos - Sec.1 - LAB - Grupo 1.01 - Docente\tLuis Gomez",
  "GH0023-Business Communication - Sec.1 - LAB - Grupo 1.01 - Docente\tKenny Neira",
  "CS1021-Matemáticas Discretas I - Sec.1 - LAB - Grupo 1.01 -  ",
  "CS1112-Programación II - Sec.1 - LAB - Grupo 1.01 - Docente\tEdson Mendiolaza",
  "AM3001-Hidrología - Sec.1 - LAB - Grupo 1.01 - Docente\tHarold Omar Llauca",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.2 - LAB - Grupo 2.05 -  ",
  "CS1021-Matemáticas Discretas I - Sec.3 - LAB - Grupo 3.01 -  ",
  "CC2104-Métodos Numéricos - Sec.7 - LAB - Grupo 7.01 - Docente\tRosulo Perez",
  ":ExF Estadística y Prob 1",
  ":Eventos UTEC",
  ":SSGG - Aldo",
  ":Asesoría EL1",
  ":Mantenimiento - SSGG",
  ":SIMULACRO 1 - PREPÁRATE UTEC",
  ":Asesoría de proyectos",
  ":asesoría",
  ":UTEC Ventures",
  ":Asesoría - Cálculo Vectorial",
  ":Silvat",
  "QI0014-Conminución - Sec.1 - TEO - Grupo 1 - Docente\tAmerico Zuñiga",
  "EL2012-Circuitos Analógicos - Sec.1 - TEO - Grupo 1 - Docente\tFrancisco Camacho",
  "EL3015-Introducción a las Telecomunicaciones - Sec.1 - TEO - Grupo 1 - Docente\tMoises Nuñez",
  "EL2081-Circuitos Eléctricos y Electrónicos I - Sec.3 - TEO - Grupo 3 - Docente\tLuis Quineche",
  "PI3103-Proyectos Interdisciplinarios 3 - Sec.4 - TEO - Grupo 4 - Docente\tManuel Chavez",
  "PI3103-Proyectos Interdisciplinarios 3 - Sec.11 - TEO - Grupo 11 - Docente\tKenny Neira",
  "CI2011-Introducción a la Mecánica de Sólidos - Sec.4 - LAB - Grupo 4.01 - Docente\tAristoteles Gerardo Figueroa",
  ":Examen Investigación de Operaciones II - Claudia Antonini",
  ":RESERVA - Daniel Marcos Chirinos",
  ":EAU - Luis Hurtado Mondoñedo",
  ":PRE UTEC",
  ":MANTENIMIENTO AUDIOVISUAL TI 2024-I",
  ":Examen Parcial de métodos numéricos ",
  ":ExF Ecuaciones diferenciales",
  ":Examen Final - Ecuaciones Diferenciales",
  ":Examen Final - Álgebra Lineal",
  ":Examen de Admisión General -  Jimena Torres",
  ":Ex-Final Ecuaciones diferenciales PReynoso",
  ":Prepárate UTEC - Kimberly Padilla",
  ":CIUR 2024 - Centro de Impacto y Responsabilidad Social -  Gabriela García",
  ":HAckathon inclusión - Veronica Lunga",
  ":Tu vocación STEM - Marilin Durand",
  ":Educamp - Olenka Noriega",
  ":Educamp docente 2024 - Olenka Burmester",
  "QI0003-Mineralogía Aplicada - Sec.1 - TEO - Grupo 1 - Docente\tAmerico Zuñiga",
  "CC1101-Cálculo de una variable - Sec.1 - TEO - Grupo 1.05 -  ",
  "CC1141-Química General - Sec.1 - TEO - Grupo 1.02 -  ",
  "AM1001-Introducción a la Ingeniería Ambiental - Sec.1 - TEO - Grupo 1 - Docente\tAkira Armando Wong",
  "IN1001-Introducción a la Ingeniería Industrial - Sec.1 - TEO - Grupo 1 -  ",
  "CC1106-Matemática para Administradores - Sec.1 - TEO - Grupo 1 - Docente\tDavy Olivera",
  "GI2101-Empresa y Consumidor - Sec.1 - TEO - Grupo 1.06 - Docente\tJosé Luis Herrán",
  "CC1101-Cálculo de una variable - Sec.2 - TEO - Grupo 2.04 - Docente\tCristian Felix Rojas",
  "CC1101-Cálculo de una variable - Sec.2 - TEO - Grupo 2.05 - Docente\tMarco Antonio Cuyubamba",
  "CC1101-Cálculo de una variable - Sec.2 - TEO - Grupo 2.02 -  ",
  "CC1101-Cálculo de una variable - Sec.2 - TEO - Grupo 2.03 -  ",
  "CC1141-Química General - Sec.2 - TEO - Grupo 2.04 -  ",
  "IN1001-Introducción a la Ingeniería Industrial - Sec.2 - TEO - Grupo 2 -  ",
  "CC1101-Cálculo de una variable - Sec.3 - TEO - Grupo 3.05 - Docente\tMarco Antonio Cuyubamba",
  "CC1101-Cálculo de una variable - Sec.3 - TEO - Grupo 3.01 -  ",
  "MT1001-Introducción a la Ingeniería Mecatrónica - Sec.3 - TEO - Grupo 3 -  ",
  "CI2012-Dinámica y Vibraciones - Sec.3 - TEO - Grupo 3 - Docente\tRick Milton Delgadillo",
  "CC1101-Cálculo de una variable - Sec.4 - TEO - Grupo 4.03 -  ",
  "CS1021-Matemáticas Discretas I - Sec.4 - TEO - Grupo 4 -  ",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.1 - LAB - Grupo 1.02 - Docente\tJavier Pizarro",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.1 - LAB - Grupo 1.01 - Docente\tEmily Baca",
  "IS1000-Introducción a Sistemas de Información - Sec.1 - LAB - Grupo 1.01 -  ",
  "AD1002-Microeconomía Aplicada - Sec.1 - LAB - Grupo 1.01 -  ",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.2 - LAB - Grupo 2.05 - Docente\tFiorella Burneo",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.2 - LAB - Grupo 2.01 - Docente\tDaniel Cespedes",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.2 - LAB - Grupo 2.02 - Docente\tJimena Muñoz",
  "HH1101-Laboratorio de Comunicación 1 - Sec.3 - LAB - Grupo 3.04 - Docente\tVioleta Reaño",
  ":Presentación final - Robótica avanzada Oscar Ramos",
  ":Asesoría Álgebra Lineal",
  ":Grabacion en salones - Karina Meier Zender",
  ":Reunión - Andrea Valencia",
  "MT0011-Robótica Avanzada - Sec.1 - TEO - Grupo 1 - Docente\tOscar Ramos",
  "CI0011-Ingeniería de Transporte I - Sec.1 - TEO - Grupo 1 - Docente\tWalter Samaniego",
  "AD1102-Taller de Planeamiento y estrategias de Aprendizaje - Sec.1 - TEO - Grupo 1 - Docente\tHector Bustamante ",
  "AM0045-Gestión Ambiental Aplicada - Sec.1 - TEO - Grupo 1 - Docente\tJose Manuel Cerdan",
  "AD2101-Economía Aplicada - Sec.1 - TEO - Grupo 1 - Docente\tMiguel Angel Velasquez",
  "IN2005-Estadística Aplicada - Sec.2 - TEO - Grupo 2 - Docente\tOrlando Alfredo Galarza",
  "IQ1002-Química Avanzada - Sec.2 - TEO - Grupo 2 - Docente\tWiliam Segura",
  "CI1002-Geometría Descriptiva - Sec.4 - TEO - Grupo 4 - Docente\tKarina Elizabeth Vilela",
  "AM0045-Gestión Ambiental Aplicada - Sec.1 - LAB - Grupo 1.01 - Docente\tJose Manuel Cerdan",
  "GH0016-Liderazgo y negociación - Sec.6 - LAB - Grupo 6.01 - Docente\tRolando Carrazco",
  "CS8137-Tesis II - Sec.1 - TEO - Grupo 1 - Docente\tJesus Bellido",
  ":Grabaciones de Marketing",
  ":Conversaión alumnos-Rocio Valenzuela",
  ":Evento Maruxa Pereyra",
  ":Evento -Escuela R",
  ":Organización Fúsica - Maruxa Pereyra",
  ":Mantenimiento TI ",
  ":Competencia de Debate Interuniversitario - UDS - Maruxa Pereyra Sotelo",
  ": Evento de Cierre La Mezcladora - UTEC Ventures - Norma Alva",
  ":Competencia de debate interuniversitario - UDS - Maruxa Pereyra Sotelo",
  ":Evento de fin de año - UTEC - Andrea Valencia Pérez",
  ":Reunión 2024 AICHE - Maruxa Pereyra Sotelo",
  ":CS-Update: Especializaciones - Julia Saenz",
  ":AIESEC - Veronica Lunga",
  ":Lima Global Experience-Angela Ramirez",
  ":Examen de Admisión - Jimena Torres",
  ":Masterclasses - Kimberly Padilla",
  ":Municipalidad  - Angela Ramírez ",
  ":UTEC Ventures con CIX BCP-Norma Alva",
  ":Reserva - Andrea Valencia Pérez",
  ":EmpowerWeek - Maruxa Pereyra",
  ":Siemens -  Veronica Lunga",
  ":Educamp docente 2024 - CE2A",
  ":Integrautec 2024-1 -- Maruxa Pereyra Sotelo",
  ":Ensayo previo a Elevator Pitch",
  ":Shift Day-Norma Alva",
  "CC1141-Química General - Sec.1 - TEO - Grupo 1 - Docente\tBetty Flores",
  "CC1141-Química General - Sec.1 - TEO - Grupo 1 -  ",
  "CS1000-Introducción a la Ciencia de la Computación - Sec.1 - TEO - Grupo 1 - Docente\tJesus Bellido",
  "HH1101-Laboratorio de Comunicación 1 - Sec.1 - TEO - Grupo 1 -  ",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.1 - TEO - Grupo 1 -  ",
  "CC1141-Química General - Sec.2 - TEO - Grupo 2 -  ",
  "HH1101-Laboratorio de Comunicación 1 - Sec.2 - TEO - Grupo 2 -  ",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.2 - TEO - Grupo 2 -  ",
  "CC1141-Química General - Sec.3 - TEO - Grupo 3 -  ",
  "HH1101-Laboratorio de Comunicación 1 - Sec.3 - TEO - Grupo 3 -  ",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.3 - TEO - Grupo 3 -  ",
  ":Clases posgrado-edux- Yaneth Claros",
  ":Escuela R-Angela Ramirez",
  ":Inducción Personal - Gestión del Talento - Luisiana Varela",
  ":Taller ASCE - Maruxa Pereyra Sotelo",
  ":Reunión planeamiento Posgrado",
  ":Clases Posgrado - Edux",
  ":Harvard-Mary Alburqueque",
  ":Harvard SEAS - Valeria Mary Alburqueque Armas",
  ":Valeria Mary Alburqueque Armas - Harvard SEAS",
  ": Strategic Agility para la Transformación Continua",
  ":Reserva - Lusiana Varela Macher",
  ":Reunión de Coordinadores Canguro Matemático",
  ":Eventos comunidad Ágil Perú",
  ":Tu vocación STEM 2024 I",
  ":REUNIÓN PROYECTORES PM",
  ":Eventos comunidad ágil",
  ":Contacto UTEC - Mibanco",
  ":Tech estudios",
  ":Mecs - Estudios ",
  ":Posgrado oficina",
  ":Exámen de Admisión - Jimena Torres",
  ":Revisión OPEX 2024 y Acciones",
  ":Reserva - Angel Malca Acuña",
  ":Focus Group - Créssida Acosta",
  ":Eventos comunidad Ágil Perú - Angel Malca",
  ":Revisión Plan de Actividades Académicas (Opex 2024) -  Angel Malca",
  ":Data Movement - Julia Saenz Alatrista",
  ":INTEGRA UTEC - Gabriela Perea",
  "GH0024-Crítica de la Modernidad - Sec.1 - TEO - Grupo 1 - Docente\tCristina Alayza",
  "CI0018-Ingeniería Geotécnica - Sec.1 - TEO - Grupo 1 - Docente\tMayu Tincopa",
  "BI2004-Termodinámica en Bioingeniería - Sec.1 - TEO - Grupo 1 - Docente\tMaria Carranza",
  "IN3012-Planificación y Control de Operaciones - Sec.1 - TEO - Grupo 1 - Docente\tJose Larco",
  "CC1122-Fundamentos de Electricidad y Magnetismo - Sec.2 - TEO - Grupo 2.06 - Docente\tSaneli Alcides Carbajal",
  "IN0066-Métodos Estadísticos Avanzados para la Calidad - Sec.1 - LAB - Grupo 1.01 - Docente\tAlejandro Gallegos",
  "AD2004-Gestión de la Información - Sec.1 - LAB - Grupo 1.01 - Docente\tPablo Andres Perez",
  "CS1022-Matemáticas Discretas II - Sec.1 - LAB - Grupo 1.01 - Docente\tJorge Tipe",
  ":ExF Óptica & Ondas",
  ":Presentación proyectos de carrera - pregrado - Valenzuela Osorio,Rocio Cecilia",
  ":EL3014 Introducción a Sistemas Embebidos Teoría 1,00 - Camacho Jiménez, Francisco José",
  ":Examen Parcial - Cálculo Vectorial",
  ":ExF Cálculo Vectorial PReynoso",
  ":IntegraUTEC: Departamento Civil y Ambiental - Marjorie Del Carmen Alayo",
  "CC1104-Cálculo Vectorial - Sec.1 - TEO - Grupo 1.02 - Docente\tCristina  Navarro",
  "CC1104-Cálculo Vectorial - Sec.1 - TEO - Grupo 1.03 - Docente\tPatricia Reynoso",
  "HH2102-Economía, Gobernanza y Relaciones de Poder - Sec.1 - TEO - Grupo 1 - Docente\tGiancarlo Espinoza",
  "HH3101-Arte y Tecnología - Sec.1 - TEO - Grupo 1 - Docente\tLuisa Fernanda Lindo",
  "CC2121-Termodinámica - Sec.1 - TEO - Grupo 1.05 - Docente\tNaudy Lopez",
  "MT2001-Dinámica de Cuerpos Rígidos - Sec.1 - TEO - Grupo 1 - Docente\tJose Luis Bohorquez",
  "IN2006-Fundamentos de Operaciones - Sec.1 - TEO - Grupo 1 - Docente\tOscar Gamonal",
  "AM2003-Geología - Sec.1 - TEO - Grupo 1 - Docente\tJuan Gomez",
  "ME3012-Mecánica de Materiales - Sec.1 - TEO - Grupo 1 - Docente\tSergio Candiotti",
  "CC2121-Termodinámica - Sec.2 - TEO - Grupo 2.02 - Docente\tNaudy Lopez",
  "IN3007-Simulación de Operaciones - Sec.2 - TEO - Grupo 2 - Docente\tGeorge Gonzalez",
  "ME2013-Estática - Sec.2 - TEO - Grupo 2 - Docente\tDavy Olivera",
  "HH2101-Perú: Temas de la sociedad contemporánea - Sec.3 - TEO - Grupo 3 - Docente\tJose Pino",
  "CI1002-Geometría Descriptiva - Sec.3 - TEO - Grupo 3 - Docente\tKarina Elizabeth Vilela",
  "GH0016-Liderazgo y negociación - Sec.7 - TEO - Grupo 7 - Docente\tMaria Rosa Moran",
  "HH2102-Economía, Gobernanza y Relaciones de Poder - Sec.11 - TEO - Grupo 11 - Docente\tJose Pino",
  "HH1101-Laboratorio de Comunicación 1 - Sec.1 - LAB - Grupo 1.01 - Docente\tJavier Pizarro",
  "HH1102-Laboratorio de Comunicación 2 - Sec.1 - LAB - Grupo 1.01 - Docente\tVeronica Caballero",
  "CS1022-Matemáticas Discretas II - Sec.2 - LAB - Grupo 2.01 - Docente\tRicardo Ramos",
  "CS1022-Matemáticas Discretas II - Sec.4 - LAB - Grupo 4.01 - Docente\tRicardo Ramos",
  ":ExF Ecuaciones Diferenciales - Teoría 1.00",
  ":ExF Ecuaciones Diferenciales - Teoría 2.00",
  ":Tesis I - Sergio Aranda",
  ":Jorge Luis Rios Agurto",
  ":Data y Fidelización ",
  ":Reunión DEU",
  ":Veronica Lunga",
  ":CHARLA CAMPOS CONFORME ",
  "QI0037-Diseño de Procesos Químicos - Sec.1 - TEO - Grupo 1 - Docente\tFrancisco Tarazona",
  "PEG002-Tesis II - Sec.1 - TEO - Grupo 1 - Docente\tPedro Rau",
  ":Tesis 1 de la Maestría en Automatización y Control - Sergio Rafael Aranda Egusquiza",
  ":American Invitation Mathematical Examination (AIME)",
  ":Reunión Equipo ChemE Cube Competition de AIChE UTEC",
  ":Integra UTEC - Charla Director A&ND - Cesar Armando Fuentes",
  "BI0006-Fisiología y Fisiopatología - Sec.1 - TEO - Grupo 1 - Docente\tHugo Manrique",
  "MT0003-Sistemas Hidráulicos y Neumáticos - Sec.1 - TEO - Grupo 1 - Docente\tLuis Enrique Garcia",
  "CC1101-Cálculo de una variable - Sec.1 - TEO - Grupo 1.03 - Docente\tCordelia Khouri",
  "CS3051-Arquitectura de Computadoras - Sec.1 - TEO - Grupo 1 - Docente\tJorge Gonzalez",
  "CC1121-Introducción a la Mecánica - Sec.1 - TEO - Grupo 1.02 - Docente\tKatia Zegarra",
  "CC1121-Introducción a la Mecánica - Sec.1 - TEO - Grupo 1.03 - Docente\tJosé Renato Sanchez",
  "IN2005-Estadística Aplicada - Sec.1 - TEO - Grupo 1 - Docente\tClaudia Antonini",
  "IQ2003-Análisis de Procesos Químicos - Sec.1 - TEO - Grupo 1 - Docente\tFrancisco Tarazona",
  "ME2014-Ingeniera de materiales - Sec.1 - TEO - Grupo 1 - Docente\tSergio Candiotti",
  "ME3013-Procesos de manufactura - Sec.1 - TEO - Grupo 1 - Docente\tCesar Nunura",
  "CC1104-Cálculo Vectorial - Sec.2 - TEO - Grupo 2.03 - Docente\tPatricia Reynoso",
  "CC2101-Ecuaciones Diferenciales - Sec.2 - TEO - Grupo 2.03 - Docente\tSergio Quispe",
  "CC1104-Cálculo Vectorial - Sec.3 - TEO - Grupo 3.01 - Docente\tCristina  Navarro",
  "IN3004-Salud y Seguridad Ocupacional - Sec.3 - TEO - Grupo 3 - Docente\tUrsula Angelica Velazco",
  "HH1102-Laboratorio de Comunicación 2 - Sec.11 - TEO - Grupo 11 - Docente\tVeronica Caballero",
  "AM2003-Geología - Sec.1 - LAB - Grupo 1.01 - Docente\tEdmundo Vereau",
  "GH0014-Culturas de Gobernanza y Distribución de Poder - Sec.2 - LAB - Grupo 2.01 - Docente\tJuan Sanchez",
  ":Evaluación Final - Gerencia de Productos Digitales I",
  ":Curso-Taller: Optimización de manuscritos para publicación",
  ":Reunion TI - Rocio Cecilia Valenzuela Osorio",
  ":Reunión TI -  Rocio Cecilia Valenzuela",
  ":Examen IMC",
  "BI0022-Nanotecnología - Sec.1 - TEO - Grupo 1 - Docente\tSthy  Flores",
  "ME2012-Dinámica - Sec.1 - TEO - Grupo 1 - Docente\tEmir Vela",
  "CI3013-Mecánica Estructural - Sec.3 - TEO - Grupo 3 - Docente\tSmith Kevin Huamani",
  "PI3103-Proyectos Interdisciplinarios 3 - Sec.27 - TEO - Grupo 27 - Docente\tOmar Bejarano",
  ":Reserva - Marilin Durand",
  "BI0016-Robótica médica - Sec.1 - TEO - Grupo 1 - Docente\tRoberto Furukawa",
  "AM0020-Seminarios en Ingeniería Ambiental - Sec.1 - TEO - Grupo 1 - Docente\tIvonne Montes",
  "CI0028-Aspectos Legales en la Construcción - Sec.1 - TEO - Grupo 1.01 - Docente\tGrethell Gladys Maria Soto",
  "BI3006-Biología Celular y Molecular - Sec.1 - TEO - Grupo 1 - Docente\tAlejandra Ratti",
  "CC2121-Termodinámica - Sec.2 - TEO - Grupo 2.03 - Docente\tNaudy Lopez",
  "AM3002-Mecánica de Fluidos Ambiental - Sec.2 - TEO - Grupo 2 - Docente\tJimmy Mendoza",
  "PI3103-Proyectos Interdisciplinarios 3 - Sec.20 - TEO - Grupo 20 - Docente\tCarlos Alberto Pereira",
  ":Concurso en la carrera de Adm. y Negocios Digitales - Verónica Lunga",
  ":Entrega de exámenes : ESTATICA Y DIBUJO Y DISEÑO PARA INGENIERIA - Jorge Arturo Morales Ortiz",
  ":Exposición - Estadística Aplicada Sección 1 - Claudia Antonini",
  ":Mantenimiento SSGG-Victor Enciso",
  ":Devolución de evaluaciones Gabriel Michhue",
  ":Otros",
  ":Exámenes de Rezagados",
  ":Clase modelo presencial - Gabriela Vera Tudela",
  ":Reunión AIESEC - Verónica Lunga",
  ":Examen Final - Ciencia de los Materiales",
  "GH0017-Introducción al Quechua - Sec.1 - TEO - Grupo 1 - Docente\tAgustín Panizo",
  "IN0090-Ingeniería Financiera - Sec.1 - TEO - Grupo 1 - Docente\tHumberto Raul Malincovich",
  "CI0025-Diseño de Estructuras Metálicas - Sec.1 - TEO - Grupo 1 - Docente\tLuis Miguel Medina",
  "CC1101-Cálculo de una variable - Sec.1 - TEO - Grupo 1.01 -  ",
  "CC1101-Cálculo de una variable - Sec.1 - TEO - Grupo 1.04 -  ",
  "CC1101-Cálculo de una variable - Sec.1 - TEO - Grupo 1.02 -  ",
  "CC1102-Pensamiento Matemático - Sec.1 - TEO - Grupo 1 - Docente\tJose Nieves",
  "CC1102-Pensamiento Matemático - Sec.1 - TEO - Grupo 1 -  ",
  "AM1001-Introducción a la Ingeniería Ambiental - Sec.1 - TEO - Grupo 1 -  ",
  "DS1000-Introducción a Ciencia de Datos - Sec.1 - TEO - Grupo 1 -  ",
  "EL1011-Introducción a la Ingeniería Electrónica - Sec.1 - TEO - Grupo 1 -  ",
  "CI1001-Introducción a la Ingeniería Civil - Sec.1 - TEO - Grupo 1 -  ",
  "ME1011-Introducción a la Ingeniería Mecánica - Sec.1 - TEO - Grupo 1 -  ",
  "AD3012-Decisiones financieras I - Sec.1 - TEO - Grupo 1 - Docente\tMilagros Cecilia Lunga",
  "CI2012-Dinámica y Vibraciones - Sec.1 - TEO - Grupo 1 - Docente\tChristian Manuel Diaz",
  "AM3007-Monitoreo Ambiental - Sec.1 - TEO - Grupo 1 - Docente\tNorvin Plumieer Requena",
  "AM3007-Monitoreo Ambiental - Sec.1 - TEO - Grupo 1 - Docente\tLlojan Chuquisengo",
  "AM3007-Monitoreo Ambiental - Sec.1 - TEO - Grupo 1 - Docente\tLidia Prisila Huaraca",
  "IS1000-Introducción a Sistemas de Información - Sec.1 - TEO - Grupo 1 -  ",
  "AD1002-Microeconomía Aplicada - Sec.1 - TEO - Grupo 1 -  ",
  "AD1003-Introducción a la Administración y Negocios Digita - Sec.1 - TEO - Grupo 1 -  ",
  "CC1101-Cálculo de una variable - Sec.2 - TEO - Grupo 2.05 -  ",
  "CI1001-Introducción a la Ingeniería Civil - Sec.2 - TEO - Grupo 2 -  ",
  "ME1011-Introducción a la Ingeniería Mecánica - Sec.2 - TEO - Grupo 2 -  ",
  "CI3051-Mecánica de Suelos - Sec.2 - TEO - Grupo 2 - Docente\tAlvaro Paulo Arones",
  "AM2003-Geología - Sec.2 - TEO - Grupo 2 - Docente\tJuan Gomez",
  "CC1101-Cálculo de una variable - Sec.3 - TEO - Grupo 3.04 - Docente\tCordelia Khouri",
  "CC1123-Óptica y Ondas - Sec.3 - TEO - Grupo 3 - Docente\tOscar Castillo",
  "CC1101-Cálculo de una variable - Sec.4 - TEO - Grupo 4.04 -  ",
  "HH1101-Laboratorio de Comunicación 1 - Sec.1 - LAB - Grupo 1.05 - Docente\tDaniel Cespedes",
  "AM3007-Monitoreo Ambiental - Sec.1 - LAB - Grupo 1.01 - Docente\tNorvin Plumieer Requena",
  "AM3007-Monitoreo Ambiental - Sec.1 - LAB - Grupo 1.01 - Docente\tLlojan Chuquisengo",
  "AD1006-Taller de Planeamiento y estrategias de Aprendizaj - Sec.1 - LAB - Grupo 1 -  ",
  "HH1101-Laboratorio de Comunicación 1 - Sec.2 - LAB - Grupo 2.01 - Docente\tVictor Ramirez",
  "HH1101-Laboratorio de Comunicación 1 - Sec.2 - LAB - Grupo 2.02 - Docente\tVictor Ramirez",
  "HH1101-Laboratorio de Comunicación 1 - Sec.2 - LAB - Grupo 2.05 - Docente\tDaniel Cespedes",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.2 - LAB - Grupo 2.03 - Docente\tArmando Millán",
  "HH1101-Laboratorio de Comunicación 1 - Sec.3 - LAB - Grupo 3.06 - Docente\tJavier Pizarro",
  "HH1101-Laboratorio de Comunicación 1 - Sec.3 - LAB - Grupo 3.01 - Docente\tVioleta Reaño",
  "HH1101-Laboratorio de Comunicación 1 - Sec.3 - LAB - Grupo 3.02 - Docente\tVioleta Reaño",
  ":ExF Métodos Numéricos CRUCES",
  ":SWE Reunión - Maruxa Pereyra Sotelo",
  ":Asesoría de métodos numéricos (Proyectos)",
  ":pre-Fernando Grillo",
  ":cambio de clase de Luis Enrique Garcia",
  ":ASESORÍA DE C1V ",
  ":Asesoría de proyectos - Sec1",
  ":Centro PRE - Edgard Portocarrero",
  ":ASESORIA CALCULO DE UNA VARIABLE",
  ":TECHMBA - Liliana Carolina Seminario",
  ":Examen Final - Fundamentos de Electricidad y Magnetismo",
  "CS1021-Matemáticas Discretas I - Sec.1 - TEO - Grupo 1 -  ",
  "CI1001-Introducción a la Ingeniería Civil - Sec.1 - TEO - Grupo 1 - Docente\tYelsin  HUANCACHOQUE",
  "CC2105-Estadística para Administradores II - Sec.1 - TEO - Grupo 1 - Docente\tFredy Vivanco",
  "CC2101-Ecuaciones Diferenciales - Sec.1 - TEO - Grupo 1.04 - Docente\tCristina  Navarro",
  "CC1122-Fundamentos de Electricidad y Magnetismo - Sec.1 - TEO - Grupo 1.01 - Docente\tCaroline Mouls",
  "CC2121-Termodinámica - Sec.1 - TEO - Grupo 1.04 - Docente\tNaudy Lopez",
  "CC1101-Cálculo de una variable - Sec.2 - TEO - Grupo 2.03 - Docente\tCristian Felix Rojas",
  "CC1101-Cálculo de una variable - Sec.3 - TEO - Grupo 3.01 - Docente\tDavy Olivera",
  "CC1101-Cálculo de una variable - Sec.3 - TEO - Grupo 3.02 - Docente\tCristian Felix Rojas",
  "CS1021-Matemáticas Discretas I - Sec.3 - TEO - Grupo 3 -  ",
  "AM0018-Curso Vivencial CSS - Sec.1 - LAB - Grupo 1 - Docente\tMaria La Torre",
  "HH1101-Laboratorio de Comunicación 1 - Sec.1 - LAB - Grupo 1.01 -  ",
  "HH1101-Laboratorio de Comunicación 1 - Sec.1 - LAB - Grupo 1.04 -  ",
  "HH1101-Laboratorio de Comunicación 1 - Sec.1 - LAB - Grupo 1.06 -  ",
  "HH1101-Laboratorio de Comunicación 1 - Sec.1 - LAB - Grupo 1.02 -  ",
  "HH1101-Laboratorio de Comunicación 1 - Sec.1 - LAB - Grupo 1.05 -  ",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.1 - LAB - Grupo 1.04 -  ",
  "AD3010-Business Analytics - Sec.1 - LAB - Grupo 1.01 - Docente\tPablo Andres Perez",
  "CS2024-Teoría de la Computación - Sec.1 - LAB - Grupo 1.01 - Docente\tAngel Gerardo Napa",
  "HH1101-Laboratorio de Comunicación 1 - Sec.2 - LAB - Grupo 2.05 -  ",
  "HH1101-Laboratorio de Comunicación 1 - Sec.2 - LAB - Grupo 2.01 -  ",
  "HH1101-Laboratorio de Comunicación 1 - Sec.2 - LAB - Grupo 2.02 -  ",
  "HH1101-Laboratorio de Comunicación 1 - Sec.2 - LAB - Grupo 2.03 -  ",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.2 - LAB - Grupo 2.03 -  ",
  "HH1101-Laboratorio de Comunicación 1 - Sec.3 - LAB - Grupo 3.02 -  ",
  "HH1101-Laboratorio de Comunicación 1 - Sec.3 - LAB - Grupo 3.01 -  ",
  "HH1101-Laboratorio de Comunicación 1 - Sec.3 - LAB - Grupo 3.04 -  ",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.3 - LAB - Grupo 3.02 - Docente\tMary Cynthia del Castillo",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.3 - LAB - Grupo 3.05 -  ",
  ":Planificación educamp 2024",
  ":Prepárate UTEC -  Kimberly Padilla",
  ":Eventos Posgrado - Oficina",
  ":Reunión Emir",
  ":Trabajo de planeamiento - MKT Posgrado",
  ":Carol Vargas Agreda",
  ":Asesoria -  Naudy R López Rodríguez",
  "IN0073-Calidad en los Servicios - Sec.1 - TEO - Grupo 1 - Docente\tMaria Belen Ortiz",
  "ME0035-Seminario de proyecto pre profesional - Sec.1 - TEO - Grupo 1.01 - Docente\tJuan Sanchez",
  "HH2101-Perú: Temas de la sociedad contemporánea - Sec.1 - TEO - Grupo 1 - Docente\tJose Pino",
  "CC1104-Cálculo Vectorial - Sec.1 - TEO - Grupo 1.04 - Docente\tCristina  Navarro",
  "CC1121-Introducción a la Mecánica - Sec.1 - TEO - Grupo 1.05 - Docente\tCaroline Mouls",
  "CC1121-Introducción a la Mecánica - Sec.1 - TEO - Grupo 1.04 - Docente\tJosé Renato Sanchez",
  "CI2011-Introducción a la Mecánica de Sólidos - Sec.1 - TEO - Grupo 1 - Docente\tAristoteles Gerardo Figueroa",
  "CC1123-Óptica y Ondas - Sec.2 - TEO - Grupo 2 - Docente\tOscar Castillo",
  "CC1121-Introducción a la Mecánica - Sec.2 - TEO - Grupo 2.02 - Docente\tAlexander Peña",
  "CC1122-Fundamentos de Electricidad y Magnetismo - Sec.2 - TEO - Grupo 2.01 - Docente\tJosé Renato Sanchez",
  "IN2004-Gestión de Costos - Sec.2 - TEO - Grupo 2 - Docente\tJose De La Puente",
  "IN2005-Estadística Aplicada - Sec.3 - TEO - Grupo 3 - Docente\tOrlando Alfredo Galarza",
  "CI1002-Geometría Descriptiva - Sec.5 - TEO - Grupo 5 - Docente\tEnrique Juarez",
  "CI2011-Introducción a la Mecánica de Sólidos - Sec.1 - LAB - Grupo 1.01 - Docente\tAristoteles Gerardo Figueroa",
  ":Clases Virtuales Patricia Araujo",
  ":Mantenimiento Aire Acondicionado",
  ":Pruebas audiovisuales",
  "ME0003-Seguridad en operaciones mineras - Sec.1 - TEO - Grupo 1 - Docente\tJose Apaza",
  "IQ2002-Análisis Químico para Ingeniería - Sec.1 - TEO - Grupo 1 - Docente\tCarmen Flores",
  "IQ3001-Fenómenos de Transporte - Sec.1 - TEO - Grupo 1 - Docente\tMargeo Javier Chuman",
  "AM3003-Microbiología Ambiental - Sec.1 - TEO - Grupo 1 - Docente\tIngrid Rabitsch",
  "BI1003-Química Aplicada - Sec.2 - TEO - Grupo 2 - Docente\tChristian Franco",
  "PI3103-Proyectos Interdisciplinarios 3 - Sec.25 - TEO - Grupo 25 - Docente\tAlejandro Gallegos",
  "GH0016-Liderazgo y negociación - Sec.11 - LAB - Grupo 11.01 - Docente\tJulian Valencia",
  ":Taller IEEE RAS - Maruxa Pereyra",
  ":Evento Ictac",
  ":Examen Rezagados",
  ":AM0018 Curso Vivencial CSS 1 - La Torre Cuadros, Maria de los Angeles",
  ":American Mathematics Competitions - AMC8",
  ":Asesoría de métodos numéricos",
  ":Examen Final de Óptica y Ondas (Teoría 2)",
  ":Asesoría",
  ":Reserva -  Jimena Torres",
  ":Cálculo de una variable",
  ":Examen Final - Intro a la Mecánica",
  "CS3903-Sistemas de Información - Sec.1 - TEO - Grupo 1 - Docente\tAlan Morante",
  "BI0033-Ingeniería Clínica - Sec.1 - TEO - Grupo 1 - Docente\tAlonso Agapito",
  "CC1101-Cálculo de una variable - Sec.1 - TEO - Grupo 1.04 - Docente\tCordelia Khouri",
  "HH2101-Perú: Temas de la sociedad contemporánea - Sec.1 - TEO - Grupo 1 -  ",
  "AD3006-Gerencia de Operaciones - Sec.1 - TEO - Grupo 1 - Docente\tLuis Gomez",
  "CC1104-Cálculo Vectorial - Sec.1 - TEO - Grupo 1.06 - Docente\tPatricia Reynoso",
  "CC1122-Fundamentos de Electricidad y Magnetismo - Sec.1 - TEO - Grupo 1 - Docente\tCaroline Mouls",
  "CI3014-Análisis Estructural - Sec.1 - TEO - Grupo 1 - Docente\tJavier Carlos Sarmiento",
  "CI3091-Planeamiento de Sistemas Urbanos - Sec.1 - TEO - Grupo 1 - Docente\tRoger Liy",
  "GI2101-Empresa y Consumidor - Sec.2 - TEO - Grupo 2.01 - Docente\tCarlos Guevara",
  "CC2121-Termodinámica - Sec.2 - TEO - Grupo 2.01 - Docente\tNaudy Lopez",
  "CS1021-Matemáticas Discretas I - Sec.5 - TEO - Grupo 5 -  ",
  "CS1021-Matemáticas Discretas I - Sec.6 - TEO - Grupo 6 -  ",
  "CS1021-Matemáticas Discretas I - Sec.1 - LAB - Grupo 1.01 - Docente\tJulio Eduardo Yarasca",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.1 - LAB - Grupo 1.05 -  ",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.2 - LAB - Grupo 2.04 -  ",
  "HH1101-Laboratorio de Comunicación 1 - Sec.3 - LAB - Grupo 3.03 -  ",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.3 - LAB - Grupo 3.04 -  ",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.3 - LAB - Grupo 3.01 -  ",
  "CS1021-Matemáticas Discretas I - Sec.6 - LAB - Grupo 6.01 - Docente\tJulio Eduardo Yarasca",
  "HH1102-Laboratorio de Comunicación 2 - Sec.9 - LAB - Grupo 9.01 - Docente\tCamila Chacon",
  "HH1102-Laboratorio de Comunicación 2 - Sec.11 - LAB - Grupo 11.01 - Docente\tVeronica Caballero",
  ":ExF Métodos Numéricos Todos",
  ":Viernes de ciencia y sociedad",
  ":Final del concurso ISC - Milagros Lunga",
  ":Evento RRHH - Lusiana Varela",
  ":Edgard Portocarrero Quiñe -  procesos de admisión",
  ":Demo Mode - Maria Rosa Gutierrez",
  ":Despedida de alumnos de intercambio - Gabriela Nicole Bellido Gonzales",
  ":Proyectos del curso CC2104",
  ":TALLER - Edgard Portocarrero",
  ":INCUVA",
  ":Tu vocación STEM_Tlmkg",
  ":Tu vocación STEM2024 I_Almacen",
  ":Tu vocación STEM_1°",
  ":Tu vocación STEM_Almacen",
  ":Recuperación de quiz",
  ":Recuperación de evaluaciones",
  ":Evento Día de la Mujer - Mariel Sifuentes",
  ":Kantaya - Angela Ramirez",
  ":Kantaya - Angela Ramírez",
  "CS2042-Base de Datos II - Sec.1 - TEO - Grupo 1 - Docente\tHeider Sanchez",
  "GI3101-Finanzas Empresariales - Sec.1 - TEO - Grupo 1.06 - Docente\tDiana Ramirez",
  "EL2011-Circuitos Eléctricos - Sec.1 - TEO - Grupo 1 - Docente\tElmer Arellanos",
  "EN2013-Máquinas Eléctricas - Sec.1 - TEO - Grupo 1 - Docente\tRicardo Escudero",
  "EL3016-Análisis de Señales y Sistemas para Bioingeniería - Sec.1 - TEO - Grupo 1 - Docente\tGabriel Michhue",
  "IN3004-Salud y Seguridad Ocupacional - Sec.4 - TEO - Grupo 4 - Docente\tKarina Gandi Lazo",
  "AD2002-Investigación de Mercados - Sec.1 - LAB - Grupo 1.01 - Docente\tRodolfo del Carmen Condorena",
  "GH0015-Imagen y Marca Personal - Sec.3 - LAB - Grupo 3.01 - Docente\tJimena Muñoz",
  "GH0016-Liderazgo y negociación - Sec.13 - LAB - Grupo 13.01 - Docente\tRolando Carrazco",
  ":Reserva Sustentación -  Claudia Antonini",
  ":Evento CITA - Pedro Rau ",
  ":Evento CITA - Pedro Rau",
  ":Summer Eng Jeopardy - Maruxa Pereyra",
  "IN8006-Análisis y Diseño de Sistemas de Manufactura y Servicios - Sec.1 - TEO - Grupo 1 - Docente\tGeorge Gonzalez",
  "GH0017-Introducción al Quechua - Sec.1 - TEO - Grupo 1 - Docente\tVictor Ramirez",
  "IN0083-Servicios Electrónicos - Sec.1 - TEO - Grupo 1 - Docente\tFernando Nuñez",
  "CC1141-Química General - Sec.1 - TEO - Grupo 1.02 - Docente\tPedro Guerrero",
  "CC1141-Química General - Sec.1 - TEO - Grupo 1.02 - Docente\tBetty Flores",
  "HH1102-Laboratorio de Comunicación 2 - Sec.1 - TEO - Grupo 1 - Docente\tVeronica Caballero",
  "CC1104-Cálculo Vectorial - Sec.1 - TEO - Grupo 1.01 - Docente\tCristina  Navarro",
  "CC2101-Ecuaciones Diferenciales - Sec.1 - TEO - Grupo 1.05 - Docente\tCesar Augusto Vergaray",
  "CC2101-Ecuaciones Diferenciales - Sec.1 - TEO - Grupo 1.02 - Docente\tCesar Augusto Vergaray",
  "CC1122-Fundamentos de Electricidad y Magnetismo - Sec.1 - TEO - Grupo 1.05 - Docente\tCaroline Mouls",
  "CC1122-Fundamentos de Electricidad y Magnetismo - Sec.1 - TEO - Grupo 1.02 - Docente\tCaroline Mouls",
  "CC1122-Fundamentos de Electricidad y Magnetismo - Sec.1 - TEO - Grupo 1.03 - Docente\tJosé Renato Sanchez",
  "CC1143-Ciencia de los Materiales - Sec.1 - TEO - Grupo 1.03 - Docente\tLoreleyn Flor Flores",
  "IQ2001-Química Orgánica Aplicada - Sec.1 - TEO - Grupo 1 - Docente\tJuan Carlos Rodríguez",
  "AM3001-Hidrología - Sec.1 - TEO - Grupo 1 - Docente\tHarold Omar Llauca",
  "CC1104-Cálculo Vectorial - Sec.2 - TEO - Grupo 2.04 - Docente\tJosé Renato Sanchez",
  "CC1121-Introducción a la Mecánica - Sec.2 - TEO - Grupo 2.03 - Docente\tJosé Renato Sanchez",
  "CC1122-Fundamentos de Electricidad y Magnetismo - Sec.2 - TEO - Grupo 2.03 - Docente\tSaneli Alcides Carbajal",
  "IN3006-Gestión de la Calidad - Sec.2 - TEO - Grupo 2 - Docente\tCintya  Garcia",
  "IN8006-Análisis y Diseño de Sistemas de Manufactura y Servicios - Sec.1 - LAB - Grupo 1.01 - Docente\tGeorge Gonzalez",
  "CS1021-Matemáticas Discretas I - Sec.6 - LAB - Grupo 6.01 -  ",
  "CC2121-Termodinámica - Sec.1 - TEO - Grupo 1.01 - Docente\tNaudy Lopez",
  ":Reserva director Giancarlo Flores",
  ":Reunión de Coordinación y Alineamiento Pre UTEC -  Luis Hurtado Mondoñedo",
  ":Asesoría de proyectos sección 2",
  ":Examen Parcial de Introducción a la Mecánica (Teoría 1.01)",
  ":counter docentes",
  ":Examen de Laboratorio de Álgebra Lineal -  Sergio Quispe Rodriguez",
  "GH0018-Introducción a Neurociencias - Sec.1 - TEO - Grupo 1 - Docente\tOscar Hidalgo",
  "CC2101-Ecuaciones Diferenciales - Sec.1 - TEO - Grupo 1.01 - Docente\tPatricia Reynoso",
  "CC1105-Estadística y Probabilidades I - Sec.1 - TEO - Grupo 1 - Docente\tHugo Cornejo",
  "CS3081-Ingeniería de Software - Sec.1 - TEO - Grupo 1 - Docente\tChristian Danniel Paz",
  "CI3032-Tecnología de los Materiales de Construcción - Sec.1 - TEO - Grupo 1 - Docente\tGian Franco Perez",
  "EL2082-Circuitos Eléctricos y Electrónicos II - Sec.1 - TEO - Grupo 1 - Docente\tMiguel Lozano",
  "IN3003-Principios de Diseño de Productos y Servicios - Sec.1 - TEO - Grupo 1 - Docente\tFrancisco Camacho",
  "AM3004-Hidrogeología - Sec.1 - TEO - Grupo 1 - Docente\tJorge Zafra",
  "MT1001-Introducción a la Ingeniería Mecatrónica - Sec.3 - TEO - Grupo 3 - Docente\tAyrton Nieves",
  "CI3071-Mecánica de Fluidos en Ingeniería Civil - Sec.3 - TEO - Grupo 3 - Docente\tCarmela Cristhy Ramos",
  "CC1101-Cálculo de una variable - Sec.4 - TEO - Grupo 4.05 - Docente\tCordelia Khouri",
  "HH2102-Economía, Gobernanza y Relaciones de Poder - Sec.5 - TEO - Grupo 5 - Docente\tGiancarlo Espinoza",
  "CS1021-Matemáticas Discretas I - Sec.7 - TEO - Grupo 7 -  ",
  "HH1101-Laboratorio de Comunicación 1 - Sec.1 - LAB - Grupo 1.03 -  ",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.1 - LAB - Grupo 1.03 -  ",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.1 - LAB - Grupo 1.01 -  ",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.1 - LAB - Grupo 1.02 -  ",
  "AM2001-Química Ambiental - Sec.1 - LAB - Grupo 1.02 - Docente\tMyra Flores",
  "HH1101-Laboratorio de Comunicación 1 - Sec.2 - LAB - Grupo 2.04 -  ",
  "HH1101-Laboratorio de Comunicación 1 - Sec.2 - LAB - Grupo 2.06 -  ",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.2 - LAB - Grupo 2.01 -  ",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.2 - LAB - Grupo 2.06 -  ",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.2 - LAB - Grupo 2.02 -  ",
  "HH1101-Laboratorio de Comunicación 1 - Sec.3 - LAB - Grupo 3.05 -  ",
  "HH1101-Laboratorio de Comunicación 1 - Sec.3 - LAB - Grupo 3.06 -  ",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.3 - LAB - Grupo 3.05 - Docente\tFiorella Burneo",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.3 - LAB - Grupo 3.01 - Docente\tJimena Muñoz",
  "CS1021-Matemáticas Discretas I - Sec.4 - LAB - Grupo 4.01 -  ",
  "EL8017-Tesis I - Sec.1 - TEO - Grupo 1 - Docente\tArturo Rojas",
  ":Proyecto Final Bioingeniería 2",
  ":Exposiciones - ORLANDO ALFREDO GALARZA GERÓNIMO",
  ":Entrega de Evaluaciones - Mecánica de Suelos Sec 2 - Alvaro Arones",
  ":Asesoría EP",
  ":Examen parcial de métodos numéricos",
  ":Examen de rezagados",
  "CC1141-Química General - Sec.1 - TEO - Grupo 1.01 - Docente\tPedro Guerrero",
  "IQ1001-Introducción a la Ingeniería Química - Sec.1 - TEO - Grupo 1 -  ",
  "CS1022-Matemáticas Discretas II - Sec.1 - TEO - Grupo 1 - Docente\tJose Fiestas",
  "CC1121-Introducción a la Mecánica - Sec.1 - TEO - Grupo 1.06 - Docente\tCaroline Mouls",
  "CC1141-Química General - Sec.2 - TEO - Grupo 2.03 - Docente\tHenry Carcamo",
  "CC1141-Química General - Sec.2 - TEO - Grupo 2.04 - Docente\tHenry Carcamo",
  "CC1141-Química General - Sec.2 - TEO - Grupo 2.01 - Docente\tPedro Guerrero",
  "CC1141-Química General - Sec.2 - TEO - Grupo 2.02 - Docente\tPedro Guerrero",
  "CS1021-Matemáticas Discretas I - Sec.2 - TEO - Grupo 2 -  ",
  "CI2031-Tecnologías Aplicadas en Ingeniería Civil - Sec.2 - TEO - Grupo 2.01 - Docente\tPatricia Santillan",
  "CC1141-Química General - Sec.3 - TEO - Grupo 3.01 - Docente\tBetty Flores",
  "CC1141-Química General - Sec.3 - TEO - Grupo 3.02 - Docente\tBetty Flores",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.1 - LAB - Grupo 1.06 -  ",
  "CS1022-Matemáticas Discretas II - Sec.1 - LAB - Grupo 1.01 - Docente\tJose Fiestas",
  "CS1021-Matemáticas Discretas I - Sec.2 - LAB - Grupo 2.01 -  ",
  "CS1021-Matemáticas Discretas I - Sec.3 - LAB - Grupo 3.01 - Docente\tJorge Tipe",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.3 - LAB - Grupo 3.06 -  ",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.3 - LAB - Grupo 3.02 -  ",
  ":Entrega de examenes finales - Introducción a la mecánica de suelos",
  ":Entrega de exámenes - Introducción a la Mecánica de Sólidos - Christian Manuel Díaz Esquivel",
  ":ECE",
  ":Asesoría Termodinámica",
  ":Centro PRE - Edgard Portocarrero Quiñe",
  ":Centro PRE -  Edgard Portocarrero",
  ":Reserva - Francisco Tarazona",
  "CI0016-Hidráulica Superficial - Sec.1 - TEO - Grupo 1 - Docente\tEmanuel Jesus Guzman",
  "GI3101-Finanzas Empresariales - Sec.1 - TEO - Grupo 1.09 - Docente\tLester Alberto Obispo",
  "CC1121-Introducción a la Mecánica - Sec.1 - TEO - Grupo 1 - Docente\tOscar Castillo",
  "CC1143-Ciencia de los Materiales - Sec.1 - TEO - Grupo 1.01 - Docente\tAlejandro Rios",
  "IN2003-Investigación de Operaciones I: Modelos Determinísticos - Sec.1 - TEO - Grupo 1 - Docente\tLuis Ernesto Flores",
  "IN3007-Simulación de Operaciones - Sec.1 - TEO - Grupo 1 - Docente\tGeorge Gonzalez",
  "HH2102-Economía, Gobernanza y Relaciones de Poder - Sec.6 - TEO - Grupo 6 - Docente\tAaron Nuñez",
  "IN0073-Calidad en los Servicios - Sec.1 - LAB - Grupo 1.01 - Docente\tMaria Belen Ortiz",
  "HH1102-Laboratorio de Comunicación 2 - Sec.16 - LAB - Grupo 16.01 - Docente\tClaudia Teresa Cabezas",
  "HH1102-Laboratorio de Comunicación 2 - Sec.12 - LAB - Grupo 12.01 - Docente\tVeronica Caballero",
  ":Evento Escuela R-Angela Ramirez",
  ":Clases Posgrado",
  ":Reunión TI - Rocío Valenzuela",
  "AD2103-Fundamentos de Finanzas - Sec.1 - TEO - Grupo 1 - Docente\tLester Alberto Obispo",
  "AM0049-Contaminación y Evaluación de Impactos en Recursos - Sec.1 - TEO - Grupo 1 - Docente\tLidia Prisila Huaraca",
  "GH0023-Business Communication - Sec.2 - TEO - Grupo 2 - Docente\tKenny Neira",
  "GH0015-Imagen y Marca Personal - Sec.3 - TEO - Grupo 3 - Docente\tJimena Muñoz",
  "HH2102-Economía, Gobernanza y Relaciones de Poder - Sec.12 - TEO - Grupo 12 - Docente\tRomina Perla Yalonetzky",
  "CS3026-Análisis y Diseño de Algoritmos - Sec.1 - LAB - Grupo 1.01 - Docente\tAngel Gerardo Napa",
  "GH0012-Economías en Desarrollo - Sec.2 - LAB - Grupo 2.01 - Docente\tJuan Sanchez",
  "GH0023-Business Communication - Sec.2 - LAB - Grupo 2.01 - Docente\tKenny Neira",
  "HH1102-Laboratorio de Comunicación 2 - Sec.4 - LAB - Grupo 4.01 - Docente\tVictor Ramirez",
  "CI2031-Tecnologías Aplicadas en Ingeniería Civil - Sec.1 - TEO - Grupo 1 - Docente\tHugo Esteban Pineda",
  ":Reserva - CE2A",
  ":Entrega de exámenes - CI2011 - Introducción a la Mecánica de Sólidos sección 1 y 4",
  ":Reuniones Departamental Dirección de HACS.",
  ":Reserva - Nadia Fernanda Martinez Fernandez",
  ":Demo Mode ",
  ":RESERVA - Victor Enciso",
  "QI0043-Operaciones de Separación Fisicoquímicas - Sec.1 - TEO - Grupo 1 - Docente\tVanessa Figueroa",
  "CI2011-Introducción a la Mecánica de Sólidos - Sec.4 - TEO - Grupo 4 - Docente\tAristoteles Gerardo Figueroa",
  ":Diego Flores Cano",
  ":Exposición de proyecto final - Diego Alberto Flores Cano",
  "ME0012-Planificación Minera - Sec.1 - TEO - Grupo 1 - Docente\tJuan Sanchez",
  "IN0077-Gestión de Compras y Mercados Electrónicos - Sec.1 - TEO - Grupo 1 - Docente\tLuis Gomez",
  "CI0019-Gestión de Costos - Sec.1 - TEO - Grupo 1 - Docente\tEnrique Juarez",
  "CI0027-Introducción a Lean Construction - Sec.1 - TEO - Grupo 1 - Docente\tEnrique Juarez",
  "CC1101-Cálculo de una variable - Sec.1 - TEO - Grupo 1.02 - Docente\tCordelia Khouri",
  "CS3026-Análisis y Diseño de Algoritmos - Sec.1 - TEO - Grupo 1 - Docente\tAngel Gerardo Napa",
  "CC1121-Introducción a la Mecánica - Sec.1 - TEO - Grupo 1.01 - Docente\tOscar Castillo",
  "CC2121-Termodinámica - Sec.1 - TEO - Grupo 1 - Docente\tNaudy Lopez",
  "CI3033-Tecnología del Concreto - Sec.1 - TEO - Grupo 1 - Docente\tManuel Jesus Salas",
  "CI3071-Mecánica de Fluidos en Ingeniería Civil - Sec.1 - TEO - Grupo 1 - Docente\tEmanuel Jesus Guzman",
  "ME3011-Mecánica de fluidos - Sec.1 - TEO - Grupo 1 - Docente\tAlfredo Hijar",
  "CC1141-Química General - Sec.2 - TEO - Grupo 2.03 -  ",
  "BI3007-Macromoléculas - Sec.2 - TEO - Grupo 2 - Docente\tAlejandra Ratti",
  "CC1121-Introducción a la Mecánica - Sec.2 - TEO - Grupo 2.05 - Docente\tCaroline Mouls",
  "CC1101-Cálculo de una variable - Sec.3 - TEO - Grupo 3.05 -  ",
  "CC1101-Cálculo de una variable - Sec.3 - TEO - Grupo 3.03 -  ",
  "CC1101-Cálculo de una variable - Sec.3 - TEO - Grupo 3.04 -  ",
  "HH1102-Laboratorio de Comunicación 2 - Sec.13 - LAB - Grupo 13.01 - Docente\tGiuliana Carrillo",
  ":Capacitación conferences",
  ":Reservado",
  ":Trabajo de investigación - Gabriela Perea Vega",
  "CI0017-Ingeniería de Carreteras - Sec.1 - TEO - Grupo 1 - Docente\tMiguel Angel Fernandez",
  "BI0026-Biomateriales - Sec.1 - TEO - Grupo 1 - Docente\tKaren Gonzales",
  "IQ3004-Transferencia de Masa - Sec.1 - TEO - Grupo 1 - Docente\tAmerico Zuñiga",
  "CI0011-Ingeniería de Transporte I - Sec.2 - TEO - Grupo 2 - Docente\tWalter Samaniego",
  "CI3091-Planeamiento de Sistemas Urbanos - Sec.2 - TEO - Grupo 2 - Docente\tFelix Andres Caicedo",
  "PI3103-Proyectos Interdisciplinarios 3 - Sec.3 - TEO - Grupo 3 - Docente\tSerapio Cazana",
  "PI3103-Proyectos Interdisciplinarios 3 - Sec.21 - TEO - Grupo 21 - Docente\tCesar Alfredo Bezada",
  ":Simposio de Hidrogeología - Pedro Rau",
  ":Reunión de Ventas - Taina",
  ":Reunión Equipo Chem-E-Car Competition de AIChE UTEC",
  ":Ex-Final Ciencia de los materiales",
  "AD1103-Fundamentos de Marketing - Sec.1 - TEO - Grupo 1 - Docente\tEdgar Javier Hernández",
  "CC2101-Ecuaciones Diferenciales - Sec.1 - TEO - Grupo 1.03 - Docente\tPatricia Reynoso",
  "PI3103-Proyectos Interdisciplinarios 3 - Sec.1 - TEO - Grupo 1 - Docente\tAlejandro Gallegos",
  "CC1122-Fundamentos de Electricidad y Magnetismo - Sec.1 - TEO - Grupo 1.02 - Docente\tKatia Zegarra",
  "CC1143-Ciencia de los Materiales - Sec.1 - TEO - Grupo 1.04 - Docente\tLoreleyn Flor Flores",
  "EL3303-Control de Procesos - Sec.1 - TEO - Grupo 1 - Docente\tJaime Antonio Huaytalla",
  "IN2004-Gestión de Costos - Sec.1 - TEO - Grupo 1 - Docente\tJose De La Puente",
  "IQ3005-Transferencia de calor - Sec.1 - TEO - Grupo 1 - Docente\tLuis Cesar Vargas",
  "AM2003-Geología - Sec.1 - TEO - Grupo 1 - Docente\tEdmundo Vereau",
  "GH0024-Crítica de la Modernidad - Sec.2 - TEO - Grupo 2 - Docente\tDiana García",
  "CC2101-Ecuaciones Diferenciales - Sec.2 - TEO - Grupo 2.04 - Docente\tOrlando Alfredo Galarza",
  "HH2102-Economía, Gobernanza y Relaciones de Poder - Sec.2 - TEO - Grupo 2 - Docente\tNorberto Barreto",
  "CC1121-Introducción a la Mecánica - Sec.2 - TEO - Grupo 2.01 - Docente\tJosé Renato Sanchez",
  "IN0069-Métodos de Teoría de Decisiones - Sec.1 - LAB - Grupo 1.01 - Docente\tLuis Ernesto Flores",
  "CI0018-Ingeniería Geotécnica - Sec.1 - LAB - Grupo 1.01 - Docente\tMayu Tincopa",
  "HH1102-Laboratorio de Comunicación 2 - Sec.3 - LAB - Grupo 3.01 - Docente\tOscar Hidalgo",
  "CS1021-Matemáticas Discretas I - Sec.8 - LAB - Grupo 8.01 -  ",
  ":Soporte TI",
  ":Cambio de Clases ",
  ":Centro Pre - Jimena Torres",
  ":Examen EL1 - Métodos Numéricos",
  ":Métodos Numéricos - Sergio Quispe Rodriguez",
  "CC1101-Cálculo de una variable - Sec.1 - TEO - Grupo 1.01 - Docente\tCordelia Khouri",
  "CC1141-Química General - Sec.1 - TEO - Grupo 1.01 - Docente\tBetty Flores",
  "CC2101-Ecuaciones Diferenciales - Sec.1 - TEO - Grupo 1.03 - Docente\tOrlando Alfredo Galarza",
  "GI3101-Finanzas Empresariales - Sec.1 - TEO - Grupo 1.07 - Docente\tCesar Alfredo Bezada",
  "HH2102-Economía, Gobernanza y Relaciones de Poder - Sec.1 - TEO - Grupo 1 - Docente\tLuz de los Angeles Sanchez",
  "CC1122-Fundamentos de Electricidad y Magnetismo - Sec.1 - TEO - Grupo 1.06 - Docente\tSaneli Alcides Carbajal",
  "CI2012-Dinámica y Vibraciones - Sec.1 - TEO - Grupo 1 - Docente\tRick Milton Delgadillo",
  "ME2013-Estática - Sec.1 - TEO - Grupo 1 - Docente\tDavy Olivera",
  "CI3013-Mecánica Estructural - Sec.2 - TEO - Grupo 2 - Docente\tSmith Kevin Huamani",
  "IN2006-Fundamentos de Operaciones - Sec.2 - TEO - Grupo 2 - Docente\tOscar Gamonal",
  "ME3012-Mecánica de Materiales - Sec.2 - TEO - Grupo 2 - Docente\tSergio Candiotti",
  "PI3103-Proyectos Interdisciplinarios 3 - Sec.3 - TEO - Grupo 3 - Docente\tJose Velarde",
  "GH0024-Crítica de la Modernidad - Sec.4 - TEO - Grupo 4 - Docente\tDiana García",
  "PI3103-Proyectos Interdisciplinarios 3 - Sec.16 - TEO - Grupo 16 - Docente\tJuan Sanchez",
  "GH0025-English for STEAM - Sec.1 - LAB - Grupo 1.01 - Docente\tClaudia Teresa Cabezas",
  "AM0049-Contaminación y Evaluación de Impactos en Recursos - Sec.1 - LAB - Grupo 1.01 - Docente\tLidia Prisila Huaraca",
  "PI1101-Proyectos Interdisciplinarios 1 - Sec.3 - LAB - Grupo 3.03 -  ",
  "CS1022-Matemáticas Discretas II - Sec.3 - LAB - Grupo 3.01 - Docente\tJose Renom",
  "GH0023-Business Communication - Sec.5 - LAB - Grupo 5.01 - Docente\tClaudia Teresa Cabezas",
  "CS1021-Matemáticas Discretas I - Sec.5 - LAB - Grupo 5.01 -  ",
  "CS1021-Matemáticas Discretas I - Sec.7 - LAB - Grupo 7.01 -  ",
  "HH1102-Laboratorio de Comunicación 2 - Sec.14 - LAB - Grupo 14.01 - Docente\tVeronica Caballero",
  "ME0008-Gestión de Equipos y Maquinarias - Sec.1 - TEO - Grupo 1 - Docente\tJose Apaza",
  "GH0016-Liderazgo y negociación - Sec.1 - TEO - Grupo 1 - Docente\tSheyla Montoya",
  "GH0016-Liderazgo y negociación - Sec.1 - TEO - Grupo 1 - Docente\tCarlos Guevara",
  "BI0034-Procesamiento y Métodos de Imágenes Biomédicas - Sec.1 - TEO - Grupo 1 - Docente\tPedro Crisostomo",
  "CC1141-Química General - Sec.1 - TEO - Grupo 1.04 -  ",
  "CS2013-Programación III - Sec.1 - TEO - Grupo 1 - Docente\tJose Armando Chavez",
  "CC1122-Fundamentos de Electricidad y Magnetismo - Sec.1 - TEO - Grupo 1.01 - Docente\tSaneli Alcides Carbajal",
  "CC2121-Termodinámica - Sec.1 - TEO - Grupo 1.06 - Docente\tNaudy Lopez",
  "CI3051-Mecánica de Suelos - Sec.1 - TEO - Grupo 1 - Docente\tGiancarlo Flores",
  "AM1003-Biología, Ecología y Recursos Naturales - Sec.1 - TEO - Grupo 1 - Docente\tMaria La Torre",
  "EL3301-Instrumentación Industrial - Sec.1 - TEO - Grupo 1 - Docente\tLuis Enrique Garcia",
  "CI0014-Análisis Estructural I - Sec.2 - TEO - Grupo 2 - Docente\tArianne Ostolaza",
  "CC1141-Química General - Sec.2 - TEO - Grupo 2.01 -  ",
  "CC1141-Química General - Sec.2 - TEO - Grupo 2.05 -  ",
  "HH2101-Perú: Temas de la sociedad contemporánea - Sec.2 - TEO - Grupo 2 - Docente\tEmily Baca",
  "HH2101-Perú: Temas de la sociedad contemporánea - Sec.2 - TEO - Grupo 2 - Docente\tGiancarlo Espinoza",
  "CC1104-Cálculo Vectorial - Sec.2 - TEO - Grupo 2.01 - Docente\tCristina  Navarro",
  "HH2102-Economía, Gobernanza y Relaciones de Poder - Sec.2 - TEO - Grupo 2 - Docente\tGiancarlo Espinoza",
  "IN3004-Salud y Seguridad Ocupacional - Sec.2 - TEO - Grupo 2 - Docente\tUrsula Angelica Velazco",
  "ME3011-Mecánica de fluidos - Sec.2 - TEO - Grupo 2 - Docente\tOmar Bejarano",
  "CC1141-Química General - Sec.3 - TEO - Grupo 3.01 -  ",
  "GH0012-Economías en Desarrollo - Sec.1 - LAB - Grupo 1.01 - Docente\tCarlos Lizarzaburu",
  "GH0016-Liderazgo y negociación - Sec.1 - LAB - Grupo 1.01 - Docente\tSheyla Montoya",
  "GH0016-Liderazgo y negociación - Sec.1 - LAB - Grupo 1.01 - Docente\tCarlos Guevara",
  "CI2011-Introducción a la Mecánica de Sólidos - Sec.3 - LAB - Grupo 3.01 - Docente\tChristian Manuel Diaz",
  "GH0023-Business Communication - Sec.4 - LAB - Grupo 4.01 - Docente\tKenny Neira",
  "DS3031-Ética y Seguridad de los Datos - Sec.1 - LAB - Grupo 1.01 - Docente\tAlan Morante",
  ":Evento ICTAC",
  ":ICTAC - Gabriela Perea",
  ":Asesoría ÁLgebra Lineal",
  ":Asesoría de Álgebra lineal",
  ":Trabajo de planeamiento y reunión con Agencia Squad",
  ": Marilin Durand",
  "CC1101-Cálculo de una variable - Sec.1 - TEO - Grupo 1.03 -  ",
  "CC1141-Química General - Sec.1 - TEO - Grupo 1.03 -  ",
  "CC1141-Química General - Sec.1 - TEO - Grupo 1.05 -  ",
  "CC1141-Química General - Sec.1 - TEO - Grupo 1.01 -  ",
  "IN1001-Introducción a la Ingeniería Industrial - Sec.1 - TEO - Grupo 1 - Docente\tCintya  Garcia",
  "MT1001-Introducción a la Ingeniería Mecatrónica - Sec.1 - TEO - Grupo 1 -  ",
  "AD3108-Emprendedurismo - Sec.1 - TEO - Grupo 1 - Docente\tCristian Gutierrez",
  "CC1104-Cálculo Vectorial - Sec.1 - TEO - Grupo 1.05 - Docente\tPatricia Reynoso",
  "CC1123-Óptica y Ondas - Sec.1 - TEO - Grupo 1 - Docente\tOscar Castillo",
  "BI3009-Principios de Biomecánica - Sec.1 - TEO - Grupo 1 - Docente\tWangdo Kim",
  "MT3001-Sensores y Actuadores - Sec.1 - TEO - Grupo 1 - Docente\tLuis Enrique Garcia",
  "CC1101-Cálculo de una variable - Sec.2 - TEO - Grupo 2.04 -  ",
  "IN1001-Introducción a la Ingeniería Industrial - Sec.2 - TEO - Grupo 2 - Docente\tJuan Bueno",
  "MT1001-Introducción a la Ingeniería Mecatrónica - Sec.2 - TEO - Grupo 2 -  ",
  "CC1121-Introducción a la Mecánica - Sec.2 - TEO - Grupo 2.04 - Docente\tCaroline Mouls",
  "CI3071-Mecánica de Fluidos en Ingeniería Civil - Sec.2 - TEO - Grupo 2 - Docente\tCarmela Cristhy Ramos",
  "CC1101-Cálculo de una variable - Sec.3 - TEO - Grupo 3.06 -  ",
  "CC1101-Cálculo de una variable - Sec.3 - TEO - Grupo 3.02 -  ",
  "CC1141-Química General - Sec.3 - TEO - Grupo 3.03 -  ",
  "GH0023-Business Communication - Sec.4 - TEO - Grupo 4 - Docente\tKenny Neira",
  "HH1102-Laboratorio de Comunicación 2 - Sec.5 - TEO - Grupo 5 - Docente\tHector Martin Canales",
  "CS1021-Matemáticas Discretas I - Sec.8 - TEO - Grupo 8 -  ",
  "IN0083-Servicios Electrónicos - Sec.1 - LAB - Grupo 1.01 - Docente\tFernando Nuñez",
  "CS3081-Ingeniería de Software - Sec.1 - LAB - Grupo 1.01 - Docente\tCarlos Balbuena",
  "CI3032-Tecnología de los Materiales de Construcción - Sec.1 - LAB - Grupo 1.01 - Docente\tElba Vasquez",
  "CI3032-Tecnología de los Materiales de Construcción - Sec.1 - LAB - Grupo 1.01 - Docente\tGian Franco Perez",
  "GH0025-English for STEAM - Sec.2 - LAB - Grupo 2.01 - Docente\tClaudia Teresa Cabezas",
  "HH1102-Laboratorio de Comunicación 2 - Sec.2 - LAB - Grupo 2.01 - Docente\tOscar Hidalgo",
];
