import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";
import "./globals.css";
import "@smastrom/react-rating/style.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          fontSans.variable,
          "bg-background font-sans antialiased min-h-screen overflow-y-scroll"
        )}
      >
        <div className="max-w-xl mx-auto min-h-screen">{children}</div>
      </body>
    </html>
  );
}
